name: punter
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - pyarrow
  - duckdb
  - scikit-learn
  - joblib
  - python-dotenv
  - requests
  - pyyaml
  - lightgbm
  - optuna
  - pytest
  - black
  - isort
  - pip
  - pip:
      - betfairlightweight
      - -e .
